# Generated by Django 3.0.6 on 2020-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200525_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
