# Generated by Django 3.0.6 on 2020-05-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200527_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-12 10:10'),
            preserve_default=False,
        ),
    ]
