# Generated by Django 3.0.6 on 2020-05-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlike',
            old_name='tweets',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='tweetlike',
            old_name='users',
            new_name='user',
        ),
    ]
